import { Link } from 'react-router-dom'
import { PageBanner, SectionHeading, TeamGrid } from '../components'
import { equipment, mission, team, vision } from '../data'

export default function About() {
  return <>
    <PageBanner eyebrow="About the directorate" title="We make room for knowledge to become ability." text="The SDE Directorate supports practical learning, responsible enterprise and student confidence at AFUED." />
    <section className="section"><div className="container story-grid"><div><SectionHeading eyebrow="Our purpose" title="A bridge between study and self-reliance." /><p className="lead">University education should strengthen both how students think and what they can confidently do.</p></div><div><p>The Skill Development & Entrepreneurship Directorate is presented as a practical learning hub where students can develop vocational ability alongside their academic programmes.</p><p>Through guided sessions, suitable equipment and repeated practice, learners can understand a craft, improve their discipline and begin to see how a useful skill becomes a service.</p></div></div></section>
    <section className="section section--soft"><div className="container director-column"><div className="director-portrait"><img src={team[0].image} alt={team[0].alt} /><small>Illustrative portrait — official photograph pending</small></div><div><p className="eyebrow">Director’s column</p><h2>Learning becomes powerful when students can apply it.</h2><p>We envision a practical learning culture where students approach tools with care, improve through repetition and understand the value of reliable work. The directorate’s role is to make that journey structured, supportive and connected to enterprise.</p><p>Every programme should leave a learner with greater confidence, a respect for quality and a clearer idea of how a skill can serve the community.</p><p className="signature"><strong>Director profile awaiting confirmation</strong><span>No successor has been publicly identified since the latest published tenure ended on 31 July 2026.</span></p></div></div></section>
    <section className="section"><div className="container values-grid values-grid--bordered"><article><p className="eyebrow">Mission</p><h2>Practical learning with purpose.</h2><p>{mission}</p></article><article><p className="eyebrow">Vision</p><h2>Ability, confidence and opportunity.</h2><p>{vision}</p></article></div></section>
    <section className="section section--green"><div className="container"><SectionHeading light eyebrow="Facilities & equipment" title="Organised for safe, repeatable practice." text="The equipment register below is illustrative until the directorate provides its official inventory." /><div className="equipment-grid">{equipment.map((item) => <article key={item.code}><span>{item.code}</span><h3>{item.name}</h3><p>{item.use}</p></article>)}</div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Our team" title="Support at every stage of practice." text="Three role-based profiles remain placeholders pending verified staff details." /><TeamGrid people={team} /></div></section>
    <section className="cta-panel"><div className="container"><p className="eyebrow">Find your environment</p><h2>See what you can learn next.</h2><Link className="button button--light" to="/sdes">Explore all SDEs</Link></div></section>
  </>
}
